apiVersion: v1
kind: Service
metadata:
    name: test-k8s
spec:
    selector:
        app: test-k8s
    ports:
        - port: 8080
          targetPort: 3000
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: test-k8s
    template:
        metadata:
            labels:
                app: test-k8s
        spec:
            containers:
                - name: test-k8s
                  image: paulserbandev/test-k8s
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '250m'
                      limits:
                          memory: '128Mi'
                          cpu: '500m'
